/** Platform Test 7 — Listening transkripti. */

export default {
  test: 'Platform Test 7 — Food & Agriculture',
  sections: [
    {
      sectionNumber: 1,
      lines: [
        ['narrator', 'Section 1. You will hear a woman ordering from a vegetable box scheme. First, you have some time to look at questions 1 to 10.'],
        ['narrator', 'Now listen carefully and answer questions 1 to 10.'],
        ['m1', 'Good morning, Green Fields Farm.'],
        ['f1', "Hello. A neighbour gets your vegetable boxes and I'd like to start one too."],
        ['m1', 'Wonderful. Can I take your name?'],
        ['f1', "Yes, Sarah Bergqvist. That's B, E, R, G, Q, V, I, S, T."],
        ['m1', 'Bergqvist, thank you. Now, we do three sizes. Small suits one person, medium is for two or three, and large for a family of four or more.'],
        ['f1', "There are two of us, and we cook most nights. I think medium."],
        ['m1', 'The medium box it is. That costs seventeen pounds.'],
        ['f1', 'Seventeen pounds per box. And how often do they come?'],
        ['m1', 'Weekly, unless you tell us otherwise. Which day would suit you?'],
        ['f1', 'Is Thursday possible?'],
        ['m1', 'Thursday is fine, we deliver in your area that day.'],
        ['f1', 'Thursday, good. What time do they arrive?'],
        ['m1', 'Deliveries arrive between seven in the morning and eleven, depending on the route.'],
        ['f1', 'Seven until eleven. I will be at work. What happens then?'],
        ['m1', 'That is not a problem. If nobody is home, boxes are left in the porch, or wherever you tell us. Just let us know a safe place.'],
        ['f1', 'The porch is fine, it is covered. Can I exclude anything? My husband will not eat mushrooms.'],
        ['m1', 'Yes, you can list up to three items. So no mushrooms, and we will substitute something else.'],
        ['f1', 'No mushrooms, thank you. Do you sell anything besides vegetables?'],
        ['m1', 'We do. Eggs from our own hens are four pounds per dozen, and we also have bread on Fridays.'],
        ['f1', 'Four pounds for eggs, yes please, add those. And if I need to change an order?'],
        ['m1', 'Orders must be changed by midday on Tuesday, because we pack on Wednesday.'],
        ['f1', 'Midday Tuesday. Where exactly is the farm, out of interest?'],
        ['m1', 'We are near Ashford, about twelve miles south of the town.'],
        ['f1', 'Near Ashford. My parents live that way. Right, could you start me next week?'],
        ['m1', 'Certainly. Your first box will arrive on Thursday.'],
        ['narrator', 'That is the end of Section 1. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 2,
      lines: [
        ['narrator', 'Section 2. You will hear a farmer speaking to visitors at the start of a farm tour. First, you have some time to look at questions 11 to 20.'],
        ['narrator', 'Now listen carefully and answer questions 11 to 20.'],
        ['f1', 'Good morning everyone, and welcome to Hollow Brook Farm. I am Kate and my family has farmed here for four generations.'],
        ['f1', "People often ask why we converted to organic methods, and they usually assume it was because of grants, or because customers demanded it. Neither is true. We changed because of soil problems. By the late nineteen nineties our soil was so depleted that yields were falling every year despite more and more fertiliser. Organic conversion was, frankly, a last resort, and it worked."],
        ['f1', "Now, a few rules before we set off. You are welcome to take as many photographs as you like. You may go into the milking parlour, and you can walk on the tracks. The one thing I must ask is that you do not feed the animals. They are on carefully controlled diets and even a handful of the wrong thing causes real problems."],
        ['f1', "Before we set off, let me take you through the layout. You should have a plan of the farm in front of you."],
        ['f1', "As you came in through the gate, the farmhouse is straight ahead of you across the yard. The farm shop is in the low building immediately to the left of the farmhouse."],
        ['f1', "The milking parlour is the long building on the right-hand side of the yard, and just beyond it, right in the corner, is the compost yard."],
        ['f1', "From the middle of the yard a track runs up between the fields. The orchard is on your left as you walk up that track."],
        ['f1', "Keep going to the end of the track and you will come to the wildlife pond, which sits in the far right-hand corner of the farm."],
        ['f1', "Let me tell you what we grow. People expect wheat, and we do grow some, along with barley for the animals. But our main crop, and what we are known for, is potatoes. About half our arable land is under potatoes in any given year."],
        ['f1', "To give you a sense of scale, the farm covers two hundred and forty hectares, which is medium-sized for this region."],
        ['f1', "Because we are organic, we cannot rely on chemicals to control pests and disease, so instead crops are rotated over a seven-year cycle. Nothing returns to the same field until the seventh year."],
        ['f1', "We also keep dairy cattle. The herd contains eighty-five dairy cows, which is small by modern standards but as many as our grassland will support."],
        ['f1', "You will notice a great many hedgerows, which most farms of this size removed decades ago. We keep them for wildlife, and hedgerows are cut only in winter, once the birds have finished nesting."],
        ['f1', "If you would like to buy anything, the farm shop opened in twenty fourteen and sells our vegetables, milk and cheese."],
        ['f1', "One thing visitors always ask about is fertility. Without artificial fertiliser, compost is made from straw and manure, turned regularly, and spread in autumn. It is not glamorous but it is the foundation of the whole system."],
        ['f1', "We will walk down through the orchard and the tour finishes at the wildlife pond, which we dug six years ago and which now has newts."],
        ['f1', 'Right, shall we make a start?'],
        ['narrator', 'That is the end of Section 2. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 3,
      lines: [
        ['narrator', 'Section 3. You will hear two students planning a study of food waste. First, you have some time to look at questions 21 to 30.'],
        ['narrator', 'Now listen carefully and answer questions 21 to 30.'],
        ['m1', 'So we have agreed on food waste. But waste where? Restaurants?'],
        ['f1', "Restaurants would need permission from the owners and they will not want us counting their bins. Supermarkets, the same problem, probably worse."],
        ['m1', 'What about primary schools?'],
        ['f1', "Ethics approval for anything involving children takes months. I think student halls is the answer. We live there, we can get access easily, and nobody has studied it here."],
        ['m1', 'Student halls, agreed. Now, how do we actually measure the waste?'],
        ['f1', 'I would say weighing bins. It is crude but it gives us a hard number, and we can do it at the same time each day.'],
        ['m1', 'Weighing bins, right. We could also ask people to record what they throw away.'],
        ['f1', 'We could, but self-reporting is unreliable for exactly this kind of thing.'],
        ['m1', 'True. Although I have a worry about the weighing too.'],
        ['f1', 'Go on.'],
        ['m1', 'If people know we are weighing their waste, they will change their behaviour when observed. They will waste less for a fortnight and then go back to normal. Our figures will look wonderful and mean nothing.'],
        ['f1', 'That is a genuine problem. We could run it for longer, so the novelty wears off.'],
        ['m1', 'Four weeks might be enough. The first week we treat as a baseline and discard.'],
        ['f1', 'Four weeks, yes. And what do we compare our results with?'],
        ['m1', 'There is a national survey published every year with household figures. That is the obvious comparison.'],
        ['f1', 'The national survey, good. What paperwork do we need?'],
        ['m1', 'We still need approval from the ethics committee, even without children, because we are collecting data about identifiable households.'],
        ['f1', 'The ethics committee, right. And units, are we measuring in kilograms?'],
        ['m1', 'Waste will be measured in kilograms each day, to one decimal place.'],
        ['f1', 'Kilograms daily. I can design the recording sheet if you like.'],
        ['m1', 'Actually, let me do the recording sheet, since I will be doing most of the weighing. You could take the analysis.'],
        ['f1', 'Fine, you do the recording sheet. How many households are we hoping for?'],
        ['m1', 'We should aim to recruit thirty households. Any fewer and one unusual flat distorts everything.'],
        ['f1', 'Thirty. And the deadline?'],
        ['m1', 'The results are presented in March, so we need to finish collecting by the end of January.'],
        ['f1', 'March. That is tight but manageable.'],
        ['narrator', 'That is the end of Section 3. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 4,
      lines: [
        ['narrator', 'Section 4. You will hear part of a lecture about feeding a growing population. First, you have some time to look at questions 31 to 40.'],
        ['narrator', 'Now listen carefully and answer questions 31 to 40.'],
        ['m1', "Good morning. The question I want to address today is a simple one to state and difficult to answer: can we feed everyone?"],
        ['m1', "Let us establish the scale. World population is expected to approach ten billion by twenty fifty, with almost all the growth in Africa and southern Asia. That is roughly two billion more people than today."],
        ['m1', "History offers some encouragement. The Green Revolution, from the nineteen sixties onwards, greatly increased cereal yields through new varieties, irrigation and mechanisation. India moved from famine to grain exports within twenty years, and the predictions of mass starvation made at the time did not come true."],
        ['m1', "But the achievement carried costs. Those yield increases have been accompanied by heavy use of fertiliser, which runs off into rivers, and by irrigation that has depleted groundwater across large regions."],
        ['m1', "Water is in fact the binding constraint in many places. Agriculture accounts for around seventy per cent of global freshwater use, far more than industry and households combined."],
        ['m1', "Land is degrading as well. Soil erosion reduces long-term productivity, and we are losing topsoil considerably faster than it forms. This is invisible year to year and severe over decades."],
        ['m1', "Then there is the question of what we eat, not merely how much. Producing meat requires far more land and water than plant foods delivering the same nutrition. Beef is the extreme case, requiring something in the order of twenty times the land per unit of protein compared with pulses."],
        ['m1', "Now for the more hopeful part. A great deal of what we already produce is never consumed, so reducing waste could feed millions without new land, without new technology and without asking anyone to eat differently."],
        ['m1', "There are technical routes as well. Crops that fix nitrogen from the air, principally legumes, reduce the need for fertiliser, and there is serious work on transferring that ability to cereals."],
        ['m1', "For regions facing a drier future, drought-resistant varieties are being developed, both by conventional breeding and by genetic modification, though the second remains politically contested in several countries."],
        ['m1', "I will end with the point that is most often missed in this debate. The world currently produces enough calories for everybody. People go hungry because of poverty, conflict and the failure of markets, not because the food does not exist. Distribution matters as much as total production, and it is a great deal harder to fix, because it is a political problem wearing an agricultural disguise."],
        ['narrator', 'That is the end of Section 4. You now have one minute to check your answers.'],
      ],
    },
  ],
};
