/** Platform Test 9 — Listening transkripti. */

export default {
  test: 'Platform Test 9 — Business & Economics',
  sections: [
    {
      sectionNumber: 1,
      lines: [
        ['narrator', 'Section 1. You will hear a woman opening a business bank account. First, you have some time to look at questions 1 to 10.'],
        ['narrator', 'Now listen carefully and answer questions 1 to 10.'],
        ['m1', 'Good morning, business banking. How can I help?'],
        ['f1', "Hello. My friend and I have started a company and we need a business account."],
        ['m1', 'Certainly. What is the name of the business?'],
        ['f1', "It's Willow Design. W, I, double L, O, W."],
        ['m1', 'Willow Design. And what is the legal structure? Sole trader, partnership, or limited company?'],
        ['f1', "We looked into it and registered as a partnership. We considered a limited company but it seemed like a lot of paperwork for now."],
        ['m1', 'A partnership, fine. And how many partners are there?'],
        ['f1', 'Two of us.'],
        ['m1', 'Two partners. Now, roughly what turnover do you expect in the first year?'],
        ['f1', 'We have projected about eighty-five thousand pounds.'],
        ['m1', 'Eighty-five thousand. That puts you in our standard business tier. The monthly account fee is twelve pounds.'],
        ['f1', 'Twelve pounds a month. Is there anything included?'],
        ['m1', 'Yes, and this is worth knowing. New businesses get a free banking period of eighteen months, so nothing at all is charged until then.'],
        ['f1', 'Eighteen months free. That is helpful when you are starting out. What do we need to bring?'],
        ['m1', 'Both partners must attend, and each needs proof of address and identity. A passport or driving licence, plus a utility bill or bank statement.'],
        ['f1', 'Proof of address and identity, for both of us. When could we come in?'],
        ['m1', 'I have an appointment on Thursday at ten in the morning.'],
        ['f1', 'Thursday at ten. That works. Who will we be seeing?'],
        ['m1', 'You will be meeting Mr Coleman, who handles new business accounts.'],
        ['f1', 'Mr Coleman. And how soon can we start using the account?'],
        ['m1', 'The account is usually open the same day, and cards arrive within seven working days.'],
        ['f1', 'Seven working days. Thank you, that is all very clear.'],
        ['narrator', 'That is the end of Section 1. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 2,
      lines: [
        ['narrator', 'Section 2. You will hear a talk given to new small business owners. First, you have some time to look at questions 11 to 20.'],
        ['narrator', 'Now listen carefully and answer questions 11 to 20.'],
        ['f1', 'Good evening everyone. I run the business support service here, and I want to spend twenty minutes on the things that actually determine whether you are still trading in three years.'],
        ['f1', "Let me start with the most important point. When businesses fail, people assume the product was poor, or that a competitor was stronger. Occasionally that is true. But by a considerable margin the most common cause of business failure is cash flow problems. Profitable businesses go under every week because money owed to them arrives after the money they owe is due. Profit is an opinion; cash is a fact."],
        ['f1', "Which leads directly to my second point. Do not leave your bookkeeping until the year end. New businesses are strongly advised to keep records weekly. It takes twenty minutes if you do it on Friday and two miserable weeks if you do it in April."],
        ['f1', "We also run a mentoring scheme, and I would encourage all of you to use it. You are matched with someone who has run a similar business, and the free mentoring scheme lasts six months."],
        ['f1', "Some context on the risks. Around fifty per cent of new businesses close within five years. That is not meant to frighten you; it is meant to make the case for preparation."],
        ['f1', "On record keeping, a legal point. Owners should keep receipts for six years, because that is how far back the tax authorities can go."],
        ['f1', "We run practical sessions here too. The workshop on marketing runs every month, and it is the one that fills up fastest, so book early."],
        ['f1', "There is money available as well. Grants are available up to five thousand pounds for equipment and training, and the fund is not usually exhausted, largely because people do not apply."],
        ['f1', "Applications require a written business plan, and it does not need to be long. Four pages that show you understand your costs and your customers is enough."],
        ['f1', "Practical details. The business centre is open until seven pm on weekdays, so you can come after work, and we open on Saturday mornings during term time."],
        ['f1', "And if you get stuck, advisers can be contacted by phone or email, and we normally reply within two working days."],
        ['f1', 'Right, I will take questions, and there is coffee at the back.'],
        ['narrator', 'That is the end of Section 2. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 3,
      lines: [
        ['narrator', 'Section 3. You will hear two students discussing a marketing case study. First, you have some time to look at questions 21 to 30.'],
        ['narrator', 'Now listen carefully and answer questions 21 to 30.'],
        ['m1', 'Have you read the case study yet?'],
        ['f1', "Twice. It is the one about the company making organic food products, the soups and sauces."],
        ['m1', 'That is the one. Food products. So what went wrong for them?'],
        ['f1', "Everyone in the seminar will say the pricing, because the products are expensive. But I do not think that is it. Their customers were happy to pay a premium. I think the real mistake was expanding too fast. They went from three regions to national distribution in eighteen months, and the supply chain simply could not support it."],
        ['m1', 'That is a much better argument, and the figures support it. Quality complaints rise exactly when the expansion starts.'],
        ['f1', 'Precisely. What do you want to add?'],
        ['m1', "I want to include data on advertising spend. They tripled it during the expansion, which tells you they were trying to solve a distribution problem with marketing."],
        ['f1', 'Advertising spend, good. That strengthens the argument rather than distracting from it.'],
        ['m1', 'And what do we recommend? Cutting costs is the obvious one.'],
        ['f1', "Obvious and wrong, I think. Cutting costs would damage the quality that was their whole proposition. And new markets would repeat the original error."],
        ['m1', 'So what then?'],
        ['f1', 'Our recommendation should focus on reducing the product range. They have forty-two lines. If they went back to fifteen, they could actually supply them reliably.'],
        ['m1', 'Reducing the range. Yes, I can defend that. How long does the report need to be?'],
        ['f1', 'The report should be ten pages, excluding appendices.'],
        ['m1', 'Ten pages. And do we need a framework?'],
        ['f1', 'She asked for one. We will use a SWOT analysis in the second section, then move to the recommendation.'],
        ['m1', 'A SWOT analysis. What was the actual damage, financially?'],
        ['f1', 'Their sales fell by thirty per cent last year, and two supermarkets dropped them entirely.'],
        ['m1', 'Thirty per cent. Should we try to speak to them?'],
        ['f1', 'I will contact the press department and see if anyone will comment. They may not, but it is worth asking.'],
        ['m1', 'The press department, good. When do we present?'],
        ['f1', 'Our seminar presentation is in week eleven.'],
        ['m1', 'Week eleven. And how does she want the references?'],
        ['f1', 'The tutor prefers references in alphabetical order, not by order of appearance. She mentioned it twice.'],
        ['m1', 'Alphabetical. Noted.'],
        ['narrator', 'That is the end of Section 3. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 4,
      lines: [
        ['narrator', 'Section 4. You will hear part of a lecture about globalisation and trade. First, you have some time to look at questions 31 to 40.'],
        ['narrator', 'Now listen carefully and answer questions 31 to 40.'],
        ['m1', "Good morning. Today I want to look at international trade: why it happens, what it has done, and why it has become so politically difficult."],
        ['m1', "The classical explanation is two centuries old and still the foundation of the subject. Trade allows countries to specialise according to comparative advantage. The important and counterintuitive part is that a country benefits from trade even if it is worse at producing everything, because what matters is relative, not absolute, efficiency."],
        ['m1', "Theory alone did not produce modern globalisation, however. Technology did. Container shipping dramatically reduced transport costs from the nineteen sixties onwards, by perhaps ninety per cent, and it did so by removing the labour of loading and unloading rather than by making ships faster."],
        ['m1', "The consequence was a reorganisation of manufacturing. Production is now organised into global supply chains, in which a single product crosses borders many times before it is finished. A car may contain components that have travelled a hundred thousand kilometres."],
        ['m1', "Now to the effects, which are genuinely mixed and are often reported dishonestly by both sides. Trade has lifted many out of poverty, most obviously in East Asia, on a scale without historical parallel. It has simultaneously increased inequality within countries, including within the countries that gained most in aggregate."],
        ['m1', "That distinction between aggregate and distribution is where the politics lives. When a factory closes because production has moved abroad, the gains are spread thinly across all consumers as slightly lower prices. The losses are concentrated on a few thousand people in one town. Regions losing factories often experience long-term unemployment, and the assumption that workers would simply move to new industries turned out to be far too optimistic."],
        ['m1', "The standard policy response is protection, and here economists are near-unanimous. Tariffs raise prices for domestic consumers, and the cost per job protected is typically several times the wage of that job."],
        ['m1', "Recent years have added a new consideration: fragility. After the disruptions of the early twenty-twenties, firms discovered that supply chains optimised for cost had no slack at all. Recent disruptions have encouraged firms to hold larger inventories, reversing forty years of just-in-time practice."],
        ['m1', "Some production is returning. Moving production closer to home is called reshoring, though the volumes remain modest and much of what returns is automated, so it brings fewer jobs than the political rhetoric implies."],
        ['m1', "Meanwhile the composition of trade is shifting. Services now account for a growing share of world trade: software, design, finance, education. Services are harder to measure and harder to tax, which is why the statistics understate them."],
        ['m1', "I will finish where I began. The argument about trade is very rarely about whether it creates wealth in total; the evidence there is strong. It is about who receives that wealth and who bears the cost. The debate is about distribution, not total wealth, and pretending otherwise is why the economics profession lost that argument publicly."],
        ['narrator', 'That is the end of Section 4. You now have one minute to check your answers.'],
      ],
    },
  ],
};
