/** Platform Test 10 — Listening transkripti. */

export default {
  test: 'Platform Test 10 — Space & Engineering',
  sections: [
    {
      sectionNumber: 1,
      lines: [
        ['narrator', 'Section 1. You will hear a woman booking places at an observatory open evening. First, you have some time to look at questions 1 to 10.'],
        ['narrator', 'Now listen carefully and answer questions 1 to 10.'],
        ['m1', 'Good evening, Bidston Hill Observatory.'],
        ['f1', "Hello. I'd like to book places for one of your open evenings, please."],
        ['m1', 'Of course. Can I take your name?'],
        ['f1', "Yes, Rachel Duffy. D, U, double F, Y."],
        ['m1', 'Duffy, thank you. How many places?'],
        ['f1', 'Four, please. Two adults and two children.'],
        ['m1', 'Four in total. And which evening?'],
        ['f1', 'The eighth of March, if there is space.'],
        ['m1', 'The eighth of March. Yes, we still have room on that one.'],
        ['f1', 'The eighth, wonderful. What does it cost?'],
        ['m1', 'Tickets are nine pounds for adults, and children under fourteen are half price.'],
        ['f1', 'Nine pounds for adults. What time should we arrive?'],
        ['m1', 'The event begins at seven thirty, but do come a few minutes early because we lock the gate.'],
        ['f1', 'Seven thirty. Is there anything we should bring?'],
        ['m1', 'The dome is unheated, so I would advise visitors to bring a blanket if it is cold. People are always surprised by how cold you get standing still.'],
        ['f1', 'A blanket, good advice. And where exactly are you? I know it is on a hill.'],
        ['m1', 'We are on Bidston Hill, at the top of the lane past the church.'],
        ['f1', 'Bidston Hill. What will we actually see?'],
        ['m1', 'It depends on conditions, but the main talk that evening is about the planet Saturn, and if the sky is clear the rings are visible through the main telescope.'],
        ['f1', 'Saturn. My daughter will be thrilled. What happens if the weather is bad?'],
        ['m1', 'Events are cancelled if the sky is cloudy, and we decide by four in the afternoon. You get a full refund or you can move to another date.'],
        ['f1', 'Cancelled if cloudy, understood. How will you let me know?'],
        ['m1', 'Confirmation is sent by text, both for the booking and for any cancellation.'],
        ['f1', 'By text, that is convenient. Thank you very much.'],
        ['narrator', 'That is the end of Section 1. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 2,
      lines: [
        ['narrator', 'Section 2. You will hear an introduction to an engineering museum. First, you have some time to look at questions 11 to 20.'],
        ['narrator', 'Now listen carefully and answer questions 11 to 20.'],
        ['f1', 'Good morning everyone, and welcome to the Museum of Engineering. I am Helen and I will give you a short introduction before you explore.'],
        ['f1', "Let me start with what people come to see. We do have an aircraft, suspended in the entrance hall, and there is a printing press on the first floor which is demonstrated regularly. But the museum's main exhibit, and the reason many visitors travel a long way, is our steam engine. It was built in eighteen forty-four, it is the oldest of its type still in working order anywhere, and we run it under steam."],
        ['f1', "Which brings me to the demonstrations. These do not run every hour, and they are not by appointment. Workshop demonstrations take place twice a day, at eleven and at three, and each lasts about forty minutes."],
        ['f1', "A safety point. Parts of the museum contain working machinery. Children under twelve must be accompanied by an adult at all times, and please keep behind the yellow lines."],
        ['f1', "Some background on the building. It was originally a railway workshop, built in eighteen sixty-two, where locomotives were repaired. Almost everything you see, including the roof, is original."],
        ['f1', "The collection has grown considerably. It now contains over twelve thousand objects, although only about a tenth are on display at any time."],
        ['f1', "For those interested in structures, the bridge gallery is on the first floor, with models of every major bridge type and a section you can load until it fails."],
        ['f1', "We are also expanding. A new gallery on renewable energy opens in June, covering wind, tidal and solar generation."],
        ['f1', "Something many visitors enjoy is watching restoration work. Volunteers restore machinery in the engine shed, at the far end of the site, and they are very happy to explain what they are doing."],
        ['f1', "About photography. You are welcome to take pictures, and photography without flash is permitted throughout, including in the archive gallery."],
        ['f1', "Finally, if you want the shop, do not leave it until the last minute, because the museum shop closes thirty minutes before the museum does."],
        ['f1', 'That is everything. Do please ask the stewards anything you like.'],
        ['narrator', 'That is the end of Section 2. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 3,
      lines: [
        ['narrator', 'Section 3. You will hear two engineering students discussing a design project. First, you have some time to look at questions 21 to 30.'],
        ['narrator', 'Now listen carefully and answer questions 21 to 30.'],
        ['f1', 'Have you looked at the project brief properly?'],
        ['m1', "I have. So we are designing a footbridge, not a turbine or anything else. Over the river, by the park."],
        ['f1', 'A footbridge, yes. Pedestrians and cyclists only, no vehicles.'],
        ['m1', 'Right. So what is the main constraint? I assumed cost.'],
        ['f1', "Cost matters, but it is not the binding one. The materials are standard and the timescale is generous. The real constraint is the span required. There is nowhere to put an intermediate pier because the riverbed is protected, so it has to cross in one go."],
        ['m1', 'How far is it?'],
        ['f1', 'The bridge must span thirty-five metres.'],
        ['m1', 'Thirty-five metres in a single span. That rules out a simple beam.'],
        ['f1', 'It does. I have been comparing a cable-stayed design against a steel arch.'],
        ['m1', 'The cable-stayed one looks more impressive, and it would be quicker to erect.'],
        ['f1', "It would. But my priority is a design that is easiest to maintain. Cables need regular inspection and eventual replacement, and this is a council footbridge that nobody will look at for twenty years. The arch is duller and it will still be standing."],
        ['m1', 'That is a fair argument. Maintenance it is. What have we still not done?'],
        ['f1', 'We have the dead load and the pedestrian loading. What we still need to calculate is wind loading, and the site is exposed.'],
        ['m1', 'Wind loading, right. I can run the stress simulation once we have those figures.'],
        ['f1', 'Good, you take the stress simulation. And presentation, do we need a physical model?'],
        ['m1', 'We do. We will build a scale model for the presentation, one to fifty.'],
        ['f1', 'A scale model. What is the design life?'],
        ['m1', 'The brief says the design must last at least sixty years with normal maintenance.'],
        ['f1', 'Sixty years. That supports the arch as well. And the budget?'],
        ['m1', 'Our budget is four hundred thousand pounds, which is realistic for this kind of structure.'],
        ['f1', 'Four hundred thousand. When is everything due?'],
        ['m1', 'The report is submitted in April, with the presentation the same week.'],
        ['f1', 'April. Then we should get the wind figures this week.'],
        ['narrator', 'That is the end of Section 3. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 4,
      lines: [
        ['narrator', 'Section 4. You will hear part of a lecture about living and working in extreme environments. First, you have some time to look at questions 31 to 40.'],
        ['narrator', 'Now listen carefully and answer questions 31 to 40.'],
        ['m1', "Good afternoon. Today I want to consider what happens to people who live and work in genuinely extreme environments, using Antarctic research stations as the main example."],
        ['m1', "Let me establish the conditions first. During the southern winter, Antarctic winter crews are isolated with no possibility of evacuation. From roughly March to October, aircraft cannot land safely. Whatever happens, medical or personal, must be dealt with on site by the people present."],
        ['m1', "Add to that the light. At the highest stations there is no sunrise for months, and continuous darkness disrupts the body's circadian rhythm. Sleep becomes fragmented, people drift later and later, and the timing of hormone release shifts."],
        ['m1', "The psychological findings are consistent across decades of study. Small groups in isolation are prone to interpersonal conflict, and it typically emerges around the middle of the winter, over matters that would be trivial anywhere else: noise, food, who cleaned what."],
        ['m1', "Performance is affected too. Monotony has measurable effects on cognitive performance, with reaction times and attention declining over the winter and recovering when the light returns."],
        ['m1', "For these reasons, selection has changed. Technical qualifications are necessary but no longer sufficient. Crew compatibility is now a major factor in selection, and candidates are assessed on how they behave in groups under stress rather than only on their expertise."],
        ['m1', "Some interventions are simple and effective. Regular contact with family improves wellbeing significantly, and satellite bandwidth, which used to be rationed severely, is now regarded as a welfare priority rather than a luxury."],
        ['m1', "This body of research has an application beyond Antarctica. Stations are used as analogues for long space missions, because the combination of isolation, confinement, small crews and no escape is the closest thing on Earth to a journey to Mars."],
        ['m1', "There is an environmental dimension as well. Under the protocols agreed in nineteen ninety-one, everything including waste must be removed from Antarctica and returned to the country of origin. Nothing may be buried or burned."],
        ['m1', "What helps people cope? The evidence points to structure. Structured routine helps maintain morale during winter: fixed mealtimes, scheduled work, organised social events. Crews that allow the timetable to dissolve do considerably worse."],
        ['m1', "I will finish with the conclusion that surprises most students. When we ask what limits human presence in extreme environments, the answer is no longer technology. We can build shelters, generate power and supply food almost anywhere. The greatest challenge is psychological rather than physical, and that is precisely the part we understand least well."],
        ['narrator', 'That is the end of Section 4. You now have one minute to check your answers.'],
      ],
    },
  ],
};
