/** Platform Test 2 — Listening transkripti. */

export default {
  test: 'Platform Test 2 — Science & Discovery',
  sections: [
    {
      sectionNumber: 1,
      lines: [
        ['narrator', 'Section 1. You will hear a woman enquiring about membership of a science museum. First, you have some time to look at questions 1 to 10.'],
        ['narrator', 'Now listen carefully and answer questions 1 to 10.'],
        ['m1', 'Good afternoon, National Science Museum, membership office.'],
        ['f1', "Hello. I'm thinking of taking out a membership and I wondered if you could explain the options."],
        ['m1', "Certainly. Could I take your name first, so I can set up a record?"],
        ['f1', "Yes, it's Claire Prentice."],
        ['m1', 'And could you spell the surname for me?'],
        ['f1', 'P, R, E, N, T, I, C, E.'],
        ['m1', 'Prentice, thank you. Now, we have three categories. Individual membership is fifty-five pounds a year. Then there is a family membership, and we also do a concession rate for students and over-sixties.'],
        ['f1', "I've got two children, so I imagine the family one would suit us."],
        ['m1', 'Then family membership is the one. That comes to ninety-six pounds annually.'],
        ['f1', 'Ninety-six pounds. And how many people does that actually cover?'],
        ['m1', 'It covers two adults and up to four children under sixteen.'],
        ['f1', "Two adults, that's perfect, my husband and myself. What do we get for that?"],
        ['m1', 'Unlimited entry to all permanent galleries, priority booking for special exhibitions, and members receive a ten per cent discount in the shop and the café.'],
        ['f1', 'Ten per cent, useful. My son is very keen on astronomy. Do you still run the planetarium?'],
        ['m1', 'We do. There are three shows a day, and the first one starts at eleven thirty. Members book that free of charge.'],
        ['f1', "Eleven thirty. He'd love that. Now, the queues at the main door are always enormous. Is there any way round that?"],
        ['m1', "Yes, that's one of the advantages. Members do not use the main entrance at all. You come in through the west entrance, on Halford Street, where there is a separate desk."],
        ['f1', 'The west entrance. That alone is worth it. And do you send out information about what is on?'],
        ['m1', 'We do. There is a monthly newsletter, and that is sent by email. We stopped posting it two years ago.'],
        ['f1', 'Email is fine. So how long before I receive the cards?'],
        ['m1', 'Your membership is active immediately, but the physical cards are printed once a week. They arrive within five working days.'],
        ['f1', 'Five working days, right.'],
        ['m1', 'And let me give you a reference number for the application. It is S, M, four, zero, two, eight.'],
        ['f1', 'S M four zero two eight. I have written that down. Thank you very much for your help.'],
        ['m1', 'My pleasure. Do enjoy your visits.'],
        ['narrator', 'That is the end of Section 1. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 2,
      lines: [
        ['narrator', 'Section 2. You will hear a talk given to visitors at a coastal research station. First, you have some time to look at questions 11 to 20.'],
        ['narrator', 'Now listen carefully and answer questions 11 to 20.'],
        ['f1', 'Welcome, everyone, to Sandhaven Coastal Research Station. My name is Ruth and I coordinate our visitor programme.'],
        ['f1', "Let me give you a little history. People sometimes assume we date from the nineteen fifties, when several similar stations were built along this coast, or from the nineteen seventies. In fact this station was established in nineteen sixty-eight, originally as an outpost of the university's marine biology department."],
        ['f1', "The focus of the work has changed considerably. For the first thirty years we were principally concerned with fish stocks, and we still keep those records. Today, however, the great majority of our work concerns coastal erosion. This stretch of coastline is retreating faster than almost anywhere else in the country, and understanding that process is now our main purpose."],
        ['f1', "Before we go outside, a word about safety. The paths are uneven and we will be near working vehicles. You do not need a helmet, and boots are not essential in this weather, but everyone must wear a high-visibility jacket at all times outside the buildings. There is a box of them by the door and please return them at the end."],
        ['f1', 'Let me tell you something about how we operate. The station employs fourteen full-time researchers, along with a number of postgraduate students who come and go.'],
        ['f1', "Our great asset is continuity. Measurements have been collected here continuously for over fifty years, which means we can distinguish a genuine trend from an unusual season. Very few stations anywhere can say that."],
        ['f1', "The main laboratory is in the north building, the low grey one behind me. The south building is accommodation and the workshop."],
        ['f1', "As for the routine, samples are collected twice each week, on Monday and Thursday, in all weather. That regularity is what makes the data usable."],
        ['f1', "We welcome school groups, but I should say that they must book at least three weeks in advance, because we need to arrange staff cover."],
        ['f1', "One important restriction. The cliff path is closed after heavy rain, sometimes for several days, because the surface becomes genuinely dangerous. Please check the noticeboard before setting out."],
        ['f1', "Finally, if you would like to see more, our annual open day is held in September, when the laboratories are open and researchers give short talks about their projects."],
        ['f1', 'Right, if you would collect a jacket, we will make a start.'],
        ['narrator', 'That is the end of Section 2. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 3,
      lines: [
        ['narrator', 'Section 3. You will hear two students discussing a laboratory report. First, you have some time to look at questions 21 to 30.'],
        ['narrator', 'Now listen carefully and answer questions 21 to 30.'],
        ['m1', 'Anna, did you get the feedback on our last report?'],
        ['f1', "I did. It was better than I expected overall, but there was one clear criticism. Dr Novak said the method section was unclear."],
        ['m1', 'Not the referencing? I was worried about the referencing.'],
        ['f1', "No, the referencing was fine, and we had all the results in. It was specifically the method. She said someone reading it could not repeat what we had done, which is the whole point of writing it."],
        ['m1', 'Fair enough. So we need to be much more precise this time.'],
        ['f1', "Exactly. Now, about the new experiment. I have been looking at the figures and I think we should run it again."],
        ['m1', 'Really? The equipment worked properly, as far as I could tell.'],
        ['f1', "It did, and the samples were fine. But one result is completely inconsistent with the other five. Trial four is so far out that either something happened that we did not record, or it is an error. I do not want to build an argument on it."],
        ['m1', 'No, you are right. Better to repeat it than explain it away.'],
        ['f1', 'Good. Now, how should we present the data? I was going to use a table.'],
        ['m1', "A table would work, but we are showing change over time, so I think a line graph is much clearer. You can see the trend immediately, and the inconsistent point stands out."],
        ['f1', 'A line graph then. Agreed.'],
        ['m1', 'And there is something we forgot last time. We need to record the room temperature during each trial, because it affects the reaction rate.'],
        ['f1', 'Room temperature, yes. I will add a column for it on the sheet.'],
        ['m1', 'What is the deadline, remind me?'],
        ['f1', 'The report has to be submitted by the twenty-second of November.'],
        ['m1', 'The twenty-second. That is tighter than I thought.'],
        ['f1', 'It is. And the maximum length is three thousand words, so we cannot pad it out.'],
        ['m1', 'Three thousand. And she wants Harvard referencing, does she not?'],
        ['f1', 'Yes, Harvard style throughout. She is strict about it.'],
        ['m1', 'Right. So, who does what?'],
        ['f1', 'I can check the error calculations, since I set up the spreadsheet last time and I know where everything is.'],
        ['m1', 'Perfect. Then I will write up the introduction and the method, properly this time.'],
        ['f1', 'And we need lab time. When are the sessions?'],
        ['m1', 'Lab sessions are available on Friday mornings. I will book us in as soon as we finish here.'],
        ['f1', 'Friday morning. That gives us two weeks to write it up.'],
        ['narrator', 'That is the end of Section 3. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 4,
      lines: [
        ['narrator', 'Section 4. You will hear part of a lecture about the scientific method in practice. First, you have some time to look at questions 31 to 40.'],
        ['narrator', 'Now listen carefully and answer questions 31 to 40.'],
        ['m1', "Good afternoon. Today I want to look at how science actually works, as opposed to how it is described in textbooks, because the difference matters a great deal."],
        ['m1', "Let us begin with the hypothesis. A scientific hypothesis is not simply a guess. The essential requirement, and this is what distinguishes science from many other activities, is that a hypothesis must be capable of being proved wrong. If no possible observation could contradict your claim, then your claim is not doing any scientific work, however true it may feel."],
        ['m1', "The second requirement concerns repetition. A single result establishes very little. If other researchers, working independently, cannot obtain the same finding, then those results lack reproducibility, and a substantial proportion of published findings in some fields turn out to fail this test."],
        ['m1', "Why does that happen? One major reason is sample size. Studies conducted on a small number of participants will, by chance alone, sometimes produce impressive-looking results. Such studies often produce results that are not reliable, and they are far more common than they should be, because small studies are cheap."],
        ['m1', "A second reason is what we call publication bias. Journals prefer positive findings. A study showing that a treatment works is interesting; a study showing that it does nothing is not, and it frequently ends up in a drawer. The consequence is that the published literature systematically overstates how well things work."],
        ['m1', "There are remedies. The most effective is to state in advance what you intend to do and what you expect to find, before collecting any data. This is known as pre-registration, and where it has been introduced, the proportion of studies reporting positive results has fallen sharply, which tells you something."],
        ['m1', "Before publication, most work goes through peer review, in which other specialists assess the manuscript. It is the main quality check we have, although it is slower and less reliable than the public generally assumes."],
        ['m1', "Let me turn to experimental design, using medicine as the example. To know whether a treatment works, you need a comparison. So one group receives the treatment, and a control group receives a placebo, an inactive substance indistinguishable from the real thing."],
        ['m1', "But that is not sufficient on its own, because expectations influence outcomes, and not only the patient's. In a double-blind trial, neither the patient nor the researcher knows who has received which. That second part is essential, because a researcher who knows will unconsciously assess patients differently."],
        ['m1', "When many studies exist on the same question, we can combine them statistically. This is called a meta-analysis, and it produces a more reliable estimate than any single study, provided the underlying studies are sound."],
        ['m1', "And I will end with the warning you have heard before but which is worth repeating, because it is violated constantly in the reporting of research: correlation does not prove causation. Two things moving together may share a cause, or the relationship may run the opposite way to the one assumed."],
        ['narrator', 'That is the end of Section 4. You now have one minute to check your answers.'],
      ],
    },
  ],
};
