/** Platform Test 8 — Listening transkripti. */

export default {
  test: 'Platform Test 8 — Culture & Travel',
  sections: [
    {
      sectionNumber: 1,
      lines: [
        ['narrator', 'Section 1. You will hear a man booking a holiday apartment. First, you have some time to look at questions 1 to 10.'],
        ['narrator', 'Now listen carefully and answer questions 1 to 10.'],
        ['f1', 'Good afternoon, Costa Verde Apartments.'],
        ['m1', "Hello. I'd like to book an apartment for next month, if you have anything free."],
        ['f1', 'I should think so. Can I take your name?'],
        ['m1', "Thomas Lindqvist. L, I, N, D, Q, V, I, S, T."],
        ['f1', 'Lindqvist, thank you. And how long would you like to stay?'],
        ['m1', 'Five nights, arriving on a Tuesday if possible.'],
        ['f1', 'Five nights. And which dates?'],
        ['m1', 'Arriving on the third of June.'],
        ['f1', 'The third of June, let me look. Yes, I can offer you apartment fourteen B, which is a one-bedroom on the second floor with a sea view.'],
        ['m1', 'Fourteen B. That sounds perfect. What does it cost?'],
        ['f1', 'The price is seventy-five euros per night at that time of year.'],
        ['m1', 'Seventy-five a night. Is anything payable in advance?'],
        ['f1', 'Yes, a deposit of one hundred euros is required to hold the booking, and it is refunded after your stay.'],
        ['m1', 'A hundred euro deposit. And what time can I get in?'],
        ['f1', 'Check-in is after three in the afternoon, because the cleaners finish at two thirty.'],
        ['m1', 'After three. And where do I collect the keys? Is there a reception?'],
        ['f1', 'There is no reception in the building, I am afraid. The keys are collected from the bakery next door, which is open until eight in the evening.'],
        ['m1', 'From the bakery. That is unusual but fine. How far is the sea?'],
        ['f1', 'The apartment is ten minutes from the beach on foot, straight down the main street.'],
        ['m1', 'Ten minutes. And are there any house rules I should know?'],
        ['f1', 'One important one. Guests must not use the terrace after ten at night. Sound carries and the neighbours complain.'],
        ['m1', 'No terrace after ten. That is reasonable. Shall I pay the deposit now?'],
        ['f1', 'If you can, yes. I will email you the confirmation and the address straight away.'],
        ['narrator', 'That is the end of Section 1. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 2,
      lines: [
        ['narrator', 'Section 2. You will hear information for visitors to a festival. First, you have some time to look at questions 11 to 20.'],
        ['narrator', 'Now listen carefully and answer questions 11 to 20.'],
        ['m1', 'Good morning and welcome to the Ashwood Festival. Let me run through the practical information before you set off.'],
        ['m1', "First, for those who have not been before, a word about what this festival is. There is live music, and there is plenty of food, and the harvest does get a mention. But the festival exists to celebrate regional crafts. Woodturning, pottery, weaving, blacksmithing. Everything you will see being made today is made by someone from within thirty miles."],
        ['m1', "Now, arriving. If you are coming by car, please do not attempt to park in the town square, which is closed, and the station car park is full by nine. Visitors arriving by car should use the park-and-ride at the showground, and buses run every ten minutes."],
        ['m1', "As for the programme, the craft demonstrations begin at ten, but the main stage performances begin at two, and run until the evening."],
        ['m1', "A little history. The festival has been held annually since nineteen seventy-eight, when it began as a single afternoon in the village hall."],
        ['m1', "It has grown somewhat. There are over ninety stalls this year, spread across the main field and the walled garden."],
        ['m1', "If you have children with you, the children's workshops take place in the blue tent, by the entrance. They are free but places are limited, so go early."],
        ['m1', "One of the highlights is the competition. Entries are on display all day and the craft competition is judged at four, with the prizes given out immediately afterwards."],
        ['m1', "A security note. Wristbands must be worn at all times, and stewards will ask to see them. If yours breaks, come to the gate and we will replace it."],
        ['m1', "If you lose something, or find something, lost property is held at the information point in the centre of the main field."],
        ['m1', "And to finish the day, the fireworks display starts at nine thirty, from the far side of the lake. The best view is from the top field."],
        ['m1', 'That is everything. Do enjoy yourselves.'],
        ['narrator', 'That is the end of Section 2. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 3,
      lines: [
        ['narrator', 'Section 3. You will hear two students discussing a cultural studies assignment. First, you have some time to look at questions 21 to 30.'],
        ['narrator', 'Now listen carefully and answer questions 21 to 30.'],
        ['f1', 'Have you started the assignment yet? I went to the museum yesterday.'],
        ['m1', "Not yet. Remind me what we actually have to do. Is it the film analysis?"],
        ['f1', "No, that was last term. This one requires us to analyse a museum exhibition. We choose one and write about how it presents its subject."],
        ['m1', 'Right, the exhibition. And what did you make of it?'],
        ['f1', "The objects are extraordinary. My problem is with the labels. They are not badly translated, and they are perfectly readable, but they are missing important context. They tell you what an object is and when it was made, and say nothing whatever about how it came to be in a museum in this country."],
        ['m1', 'That is exactly the sort of thing the module is about. We should make that our main argument.'],
        ['f1', 'Agreed. Now, what should we include as evidence?'],
        ['m1', 'I thought we could interview visitors, ask them what they took away from it.'],
        ['f1', "I am not convinced. Interviews would need ethics approval and we have three weeks. I would rather spend the time on close analysis of the objects themselves."],
        ['m1', 'But without visitors we are only describing our own reaction.'],
        ['f1', 'We can support it with the published literature on museum interpretation. Honestly, I think interviews will sink us.'],
        ['m1', 'Let us leave it out then, though I still think it would have been stronger. I will do something else instead. I want to go back and speak to a curator.'],
        ['f1', 'That is a better use of the time, and they usually agree if you email in advance.'],
        ['m1', 'I will email today. How much is this worth, remind me?'],
        ['f1', 'It is worth forty per cent of the module mark, so it matters.'],
        ['m1', 'Forty per cent. And how many objects do we have to cover?'],
        ['f1', 'We must analyse at least three objects in detail. More than that and we will not have space.'],
        ['m1', 'Three objects. When is it due?'],
        ['f1', 'The deadline is the twenty-eighth of February.'],
        ['m1', 'The twenty-eighth. Right, how shall we split it?'],
        ['f1', "I will write about the exhibition's narrative, how the story is constructed across the rooms."],
        ['m1', 'And I will take the individual objects and the curator interview. Can we use photographs?'],
        ['f1', 'We need permission to use images in the report. The museum grants it for academic work but you have to ask.'],
        ['m1', 'I will ask when I email. One more thing, is it expensive to get in?'],
        ['f1', 'Not if you plan it. The museum is free on the first Sunday of each month.'],
        ['m1', 'First Sunday. I will go then.'],
        ['narrator', 'That is the end of Section 3. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 4,
      lines: [
        ['narrator', 'Section 4. You will hear part of a lecture about cultural identity in a global world. First, you have some time to look at questions 31 to 40.'],
        ['narrator', 'Now listen carefully and answer questions 31 to 40.'],
        ['f1', "Good afternoon. Today I want to examine what happens to cultural identity when goods, people and images move around the world as freely as they now do."],
        ['f1', "The starting observation is straightforward. Globalisation has increased the movement of cultural products worldwide, and at a speed that has no precedent. A film released in Los Angeles appears in Jakarta the same week; a song recorded in Lagos is heard in Berlin within days."],
        ['f1', "The pessimistic reading of this is well known. Critics argue that the process leads to cultural homogenisation: that everywhere begins to look like everywhere else, that local forms are displaced by whichever culture has the largest export industry, and that in a century there will be one global culture with regional decoration."],
        ['f1', "There is a competing account, and the evidence is rather on its side. Others describe the result as cultural hybridity rather than loss. What actually happens when a global form arrives is that it is taken up, altered and combined with what was already there, producing something that did not exist before and is not a copy of either parent."],
        ['f1', "This process is easy to observe. Local markets often adapt global products to their own tastes, and the adaptation is not superficial. Fast food chains reformulate their menus; imported musical genres acquire local instruments, languages and subject matter, and are then exported back."],
        ['f1', "Population movement complicates the picture further. Migration creates communities with multiple identities, in which people are entirely at home in more than one cultural world and move between them according to context. The older assumption that a person has one culture, inherited and fixed, describes very few people accurately."],
        ['f1', "Among the markers people use to signal belonging, language is one of the strongest markers of identity, which is why language policy generates political heat out of all proportion to its practical consequences."],
        ['f1', "Here I want to introduce an idea that students often find unsettling. Traditions are often deliberately invented rather than simply inherited. Many national costumes, ceremonies and supposedly ancient customs were designed within the last two hundred years, frequently to support a new nation state. This does not make them fake; it makes them historical objects like any other."],
        ['f1', "Tourism intersects with all of this. Tourism can encourage the performance of local customs for visitors, and the effects are genuinely mixed. Practices that were dying have been revived because visitors will pay to see them, and simultaneously they can become fixed, simplified and detached from the life they came from."],
        ['f1', "In response, UNESCO lists intangible cultural heritage for protection, covering practices, oral traditions and craft skills rather than buildings. The list has raised the status of many traditions, though critics note that the act of listing itself changes what is listed."],
        ['f1', "The conclusion I would like you to take away is this. Cultures are best seen as dynamic rather than fixed. They have always borrowed, absorbed and changed. What is new is not the fact of change but its speed, and that is a difference of degree which may, at some point, become a difference of kind."],
        ['narrator', 'That is the end of Section 4. You now have one minute to check your answers.'],
      ],
    },
  ],
};
