/**
 * Platform Test 1 — Listening transkripti.
 * Har bir javob matnda tabiiy tarzda eshitiladi (IELTS uslubi).
 * Spikerlar: narrator, m1/m2 (erkak), f1/f2 (ayol)
 */

export default {
  test: 'Platform Test 1 — Nature & Environment',
  sections: [
    {
      sectionNumber: 1,
      lines: [
        ['narrator', 'Section 1. You will hear a man enquiring about membership at a community sports centre. First, you have some time to look at questions 1 to 10.'],
        ['narrator', 'Now listen carefully and answer questions 1 to 10.'],
        ['f1', 'Good morning, Riverside Community Sports Centre. How can I help you?'],
        ['m1', "Oh, good morning. I'd like to join the centre, please. Could you tell me what I need to do?"],
        ['f1', "Of course. I can take your details over the phone now. Can I start with your name?"],
        ['m1', "Yes, it's Peter Harding."],
        ['f1', 'And how do you spell the family name?'],
        ['m1', 'H, A, R, D, I, N, G. Harding.'],
        ['f1', 'Thank you. And your address?'],
        ['m1', "It's forty-two Wexford Road. That's W, E, X, F, O, R, D."],
        ['f1', 'Forty-two Wexford Road. And the postcode?'],
        ['m1', 'B, L, nine, four, T, R.'],
        ['f1', "Lovely. Now, we have three types of membership. There's full membership, which gives you access at any time, that's forty-five pounds a month. Then there's off-peak, which is weekdays before four in the afternoon, and that's twenty-eight pounds. And we have a student rate as well."],
        ['m1', "Well, I work from home, so I could come in the mornings. I'll take the off-peak one, please."],
        ['f1', 'Off-peak membership, that comes to twenty-eight pounds per month.'],
        ['m1', 'Twenty-eight, right. And is there a joining fee on top of that?'],
        ['f1', 'No, not at the moment. And your first induction session is free.'],
        ['m1', "Induction? What does that involve?"],
        ['f1', 'One of our instructors takes you round the gym, shows you how the equipment works and sets up a programme for you. It lasts forty-five minutes.'],
        ['m1', "Forty-five minutes. That's useful. Now, I'm mainly interested in swimming. Is the pool open all day?"],
        ['f1', "Almost. The only thing to be aware of is that the pool is closed on Tuesday mornings, because we run school lessons then. Every other morning it's open from six."],
        ['m1', 'Closed Tuesday mornings. Fine. And what about lockers, do I need coins?'],
        ['f1', 'No, our lockers are free, but members do need to bring a padlock. We had a lot of problems with the old coin system, so we changed it.'],
        ['m1', "A padlock, right, I'll remember that. One more thing, is there parking?"],
        ['f1', "Yes, there's a car park at the rear of the building. It's free for the first two hours, and after that there's a small charge."],
        ['m1', 'Two hours free. That should be plenty.'],
        ['f1', 'It usually is. Now, the last thing I should mention is cancellation. If you decide to leave, we ask for one month notice in writing or by email.'],
        ['m1', 'One month. That seems reasonable.'],
        ['f1', "It is. So that's everything. I'll send you a confirmation email today and your card will be ready to collect at reception from Monday."],
        ['m1', "That's great. Thank you very much for your help."],
        ['narrator', 'That is the end of Section 1. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 2,
      lines: [
        ['narrator', 'Section 2. You will hear a guide giving information to visitors at a botanical garden. First, you have some time to look at questions 11 to 20.'],
        ['narrator', 'Now listen carefully and answer questions 11 to 20.'],
        ['f1', 'Good afternoon everyone, and welcome to Ashcombe Botanical Garden. Before we begin, let me tell you a little about where you are.'],
        ['f1', "People often assume this was once a private estate, or a public park built for the town. In fact, neither is true. The garden was created in eighteen thirty-two as a research collection, by a group of botanists who wanted somewhere to study plants brought back from overseas expeditions. It only opened to the public much later."],
        ['f1', "Now, a few practical points. You're very welcome to take photographs anywhere in the garden, including inside the buildings. You may walk on the grass, and there's no need to keep to the paths. The one thing we do ask is that you don't bring food into the glasshouse. The humidity attracts insects, and food makes the problem considerably worse. There's a café if you'd like to eat."],
        ['f1', "If you'd like a guided tour, one leaves every hour. Please note that tours do not start from the main gate, and not from the shop either, although people often wait there by mistake. They depart from the lily pond, which is in the centre of the garden, just beyond the café terrace."],
        ['f1', "Let me mention a few of the highlights. The tropical glasshouse is kept at a constant twenty-four degrees all year round, which is why it feels so warm when you walk in from outside."],
        ['f1', "In the arboretum you'll find the oldest tree in our collection, a cedar planted in eighteen forty-six. It's now over thirty metres tall."],
        ['f1', "Behind the glasshouse is our seed bank, which currently stores more than nine thousand species. Much of that material comes from habitats that are now threatened."],
        ['f1', "We're very fortunate to have a large team of volunteers. They work mainly in the walled garden, where they've restored the original Victorian planting over the past ten years."],
        ['f1', "Do come back for our events. The autumn apple festival takes place in October, with tastings of over sixty varieties, and there's a spring concert series in May."],
        ['f1', "For anyone who needs one, wheelchairs can be borrowed free of charge from the information desk near the entrance. Please just leave a contact number."],
        ['f1', "And finally, opening hours. We're open from ten in the morning, and in summer the garden stays open until eight. Do remember that in winter the garden closes at four, as it gets dark early and the paths aren't lit."],
        ['f1', 'Right, that concludes the introduction. Please enjoy your visit.'],
        ['narrator', 'That is the end of Section 2. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 3,
      lines: [
        ['narrator', 'Section 3. You will hear two students discussing plans for a field project. First, you have some time to look at questions 21 to 30.'],
        ['narrator', 'Now listen carefully and answer questions 21 to 30.'],
        ['f1', "Tom, have you got a minute? We need to sort out the project before Thursday."],
        ['m1', "Yes, definitely. I've been worrying about it. Did you speak to Dr Ellis about our topic?"],
        ['f1', "I did, and we have a problem. Apparently another group has chosen almost exactly the same subject. There's too much overlap, so she's asked us to change."],
        ['m1', "Really? So it's not that the data isn't available, or that the site's too far?"],
        ['f1', "No, nothing like that. Purely that it overlaps with the other group's work."],
        ['m1', 'Right. Well, better to find out now than in March. So what shall we do instead?'],
        ['f1', "I thought we could look at how people actually use the new park in the town centre. Nobody's studied it."],
        ['m1', "I like that. And we can use the questionnaire we've already drafted, more or less."],
        ['f1', "About the questionnaire. What did you think of it, honestly?"],
        ['m1', "Honestly? It's too long. Thirty-two questions is far too many. People will start it and give up halfway through. The wording is clear enough, I don't have a problem with that, but it needs cutting down to about fifteen."],
        ['f1', "You're probably right. Let's cut it. Now, when should we collect the data? I was thinking weekdays only, so it's consistent."],
        ['m1', "I'd say we need both weekdays and weekends. The whole point is who uses the space, and that will be completely different on a Saturday. If we only do weekdays we'll miss families."],
        ['f1', 'Good point. Both, then. Though that does worry me about the sample.'],
        ['m1', 'In what way?'],
        ['f1', "Well, we're students, we'll be collecting in the middle of the day, and we'll approach people who look approachable. I think our sample will end up biased towards students. It won't represent the town."],
        ['m1', "That's fair. We should mention it as a limitation, and try to vary the times."],
        ['f1', "Agreed. Now, how do we present the findings? I was going to suggest a pie chart for the age groups."],
        ['m1', "A bar chart would be clearer, I think, especially if we're comparing weekday and weekend figures side by side."],
        ['f1', "Yes, a bar chart. Let's do that. And the deadline for the draft is the fourteenth of March, isn't it?"],
        ['m1', "The fourteenth, yes. The final version is in April."],
        ['f1', "Then we should start soon. Do we need permission to survey in the park?"],
        ['m1', "We do, it's council land. I'll contact the council office this week and ask."],
        ['f1', "Thanks. And how many people are we aiming for? Dr Ellis said a hundred minimum."],
        ['m1', "Let's aim for a hundred and twenty. That gives us room if some responses are unusable."],
        ['f1', "A hundred and twenty. Right. I'll take on the literature review section, since I've already read most of the background papers."],
        ['m1', "Perfect, and I'll do the methodology. Shall we check with Dr Ellis before we start?"],
        ['f1', "Yes. She's available on Thursday afternoons, so let's go then."],
        ['m1', 'Thursday afternoon it is.'],
        ['narrator', 'That is the end of Section 3. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 4,
      lines: [
        ['narrator', 'Section 4. You will hear part of a lecture about reducing food waste. First, you have some time to look at questions 31 to 40.'],
        ['narrator', 'Now listen carefully and answer questions 31 to 40.'],
        ['m1', "Good morning. Today I want to talk about food waste, which is one of those problems that is enormous, well documented, and almost entirely solvable."],
        ['m1', "Let me begin with the headline figure. Roughly one third of all the food produced in the world is never eaten. It is grown, harvested, transported, and then thrown away. If that were a country, it would be the third largest emitter of greenhouse gases on the planet."],
        ['m1', "Now, where in the chain does this happen? The answer depends very much on where you are. In wealthy countries, most waste occurs at the consumer stage. That is, in homes, restaurants and supermarkets, at the very end of the chain, after all the energy and water has already been spent on producing it."],
        ['m1', "In lower-income countries the picture is reversed. Very little is wasted in the home, because food is expensive relative to income. Instead, losses happen mainly during storage and transport, before the food ever reaches a market. Grain spoils in damp warehouses, produce rots on the way to the city because there is no refrigeration."],
        ['m1', "Let me look at consumer waste in more detail, because that is where most of you can act. A surprisingly large share of it comes down to confusion over date labels. There is a real difference between use by and best before. Use by is a safety instruction. Best before is a quality guideline, and food is very often perfectly fine after that date. Studies suggest that misunderstanding this single distinction accounts for around a fifth of household waste."],
        ['m1', "I mentioned emissions a moment ago. To put a number on it, food waste is responsible for around eight per cent of global greenhouse gas emissions. That is more than the aviation industry, by a considerable margin."],
        ['m1', "So what works? Let me give you two policy examples. South Korea introduced a scheme in which households are charged by the weight of food waste they discard. Bins are fitted with scales, and you pay for what you throw away. Household food waste fell by about a third."],
        ['m1', "In France, supermarkets are banned from discarding unsold edible food. They must donate it to charities instead. The law is not perfect, but it changed the default."],
        ['m1', "At an individual level, the research is consistent and rather boring. The single most useful habit is planning. Decide what you will cook, then write a shopping list, and buy from the list. Households that do this waste substantially less than those who shop without one."],
        ['m1', "Storage matters too, and there are some counterintuitive details. For example, storing potatoes away from onions keeps them fresh for much longer, because onions release gases that cause potatoes to sprout."],
        ['m1', "But if I had to name the most effective single measure, at home and especially in canteens and restaurants, it is reducing portion sizes. Smaller portions, with the option of more, consistently reduce plate waste by more than any awareness campaign."],
        ['m1', "In the second half of the lecture we will look at how supermarkets forecast demand, and why that forecasting produces waste further back down the supply chain."],
        ['narrator', 'That is the end of Section 4. You now have one minute to check your answers.'],
      ],
    },
  ],
};
