/** Platform Test 6 — Listening transkripti. */

export default {
  test: 'Platform Test 6 — Education & Learning',
  sections: [
    {
      sectionNumber: 1,
      lines: [
        ['narrator', 'Section 1. You will hear a woman enrolling on an evening language course. First, you have some time to look at questions 1 to 10.'],
        ['narrator', 'Now listen carefully and answer questions 1 to 10.'],
        ['m1', 'Good evening, Bridgeway Adult Education. How can I help?'],
        ['f1', "Hello. I'd like to enrol on one of your evening language courses."],
        ['m1', 'Certainly. Can I take your name?'],
        ['f1', "Yes, it's Maria Andersen. A, N, D, E, R, S, E, N."],
        ['m1', 'Andersen, thank you. And which language?'],
        ['f1', "Spanish, please. I'm going to be working with colleagues in Madrid next year."],
        ['m1', 'Spanish. And what level would you say you are?'],
        ['f1', "I studied it at school and I can hold a simple conversation, but I wouldn't call myself advanced."],
        ['m1', 'That sounds like intermediate. We have beginner, intermediate and advanced, and intermediate would suit you.'],
        ['f1', 'Intermediate, then. When does it run?'],
        ['m1', 'The intermediate group meets on Tuesday evenings, from six thirty to eight thirty.'],
        ['f1', 'Tuesday evenings. That works for me. How many weeks?'],
        ['m1', 'The course runs for ten weeks, finishing just before Christmas.'],
        ['f1', 'Ten weeks. And what does it cost?'],
        ['m1', 'The total fee is two hundred and ten pounds, which can be paid in two instalments if you prefer.'],
        ['f1', 'Two hundred and ten. And where do the classes take place?'],
        ['m1', 'Classes are held in room B twelve, which is on the lower ground floor of the main building.'],
        ['f1', 'B twelve. Do I need to buy any materials?'],
        ['m1', 'There is a course textbook, and that costs eighteen pounds extra. We sell it at reception on the first evening.'],
        ['f1', 'Eighteen pounds. Is there anything I need to do before I start?'],
        ['m1', 'Yes, one thing. A placement test must be completed online, just so we can confirm the level. It takes about twenty minutes and there is no pass or fail.'],
        ['f1', 'A placement test online, right. And who teaches the class?'],
        ['m1', "The intermediate group is taught by Elena. She's a native speaker and she's been with us for six years."],
        ['f1', 'Elena. That all sounds good. Could you send me the details?'],
        ['m1', 'I will email everything this evening, including the link to the test.'],
        ['narrator', 'That is the end of Section 1. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 2,
      lines: [
        ['narrator', 'Section 2. You will hear a talk given to new university students. First, you have some time to look at questions 11 to 20.'],
        ['narrator', 'Now listen carefully and answer questions 11 to 20.'],
        ['f1', 'Welcome, everyone. My name is Dr Sharma and I am the director of studies for your first year.'],
        ['f1', "Let me begin with what I think is the single most important thing to understand. Students often assume the difficulty of university will be academic, and that they will struggle with the material. In practice, most of you will cope with the content. The biggest adjustment, by a long way, is managing your own time. Nobody will tell you to start the essay. Nobody will notice if you do not attend. That freedom is the point of the system and it is also what defeats people."],
        ['f1', "Related to that, my advice about tutors. Do not wait until you are in serious difficulty, and do not wait until after the first assessment. Contact your tutor at the first sign of difficulty, even if it feels trivial. Problems that are easy to solve in October are extremely hard to solve in May."],
        ['f1', "Now, some practical arrangements. There is a library induction next week. It is not compulsory, but I would say it is strongly recommended, particularly the session on searching databases, which will save you many hours."],
        ['f1', "About teaching. Lectures typically last fifty minutes, and there is a ten minute gap to get between buildings."],
        ['f1', "The expectation about workload surprises people. In addition to timetabled classes, you should expect around twenty hours of independent study each week. If you are doing three, you are not doing the course."],
        ['f1', "If writing is a concern, and it is for most first-years, the writing support service is on the second floor of the library. It is free and it is not remedial; strong students use it too."],
        ['f1', "A word about deadlines. Late submissions lose five marks per day, including weekends, and after seven days the work is not marked at all. Extensions exist but must be requested in advance."],
        ['f1', "If money becomes a problem, and for some of you it will, contact the finance office early. There are hardship funds that go unclaimed every year because students do not know about them."],
        ['f1', "Similarly, the counselling service is free and confidential. Nothing you say there is passed to your department."],
        ['f1', "And finally, one deadline you must not miss. Module choices must be confirmed by the fifteenth of October. After that the system closes and changes require paperwork."],
        ['f1', 'That is everything from me. Enjoy your first year.'],
        ['narrator', 'That is the end of Section 2. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 3,
      lines: [
        ['narrator', 'Section 3. You will hear two trainee teachers discussing their school placement. First, you have some time to look at questions 21 to 30.'],
        ['narrator', 'Now listen carefully and answer questions 21 to 30.'],
        ['m1', 'How was your first week? Mine was harder than I expected.'],
        ['f1', "Mixed. The class was not badly behaved at all, which is what I had been dreading, and they seemed motivated. The difficulty is that they are very mixed in ability. I have pupils reading two years ahead and pupils who cannot access the worksheet at all, in the same room."],
        ['m1', 'That is the thing nobody prepares you for. How are you handling it?'],
        ['f1', 'Badly, so far. What about you?'],
        ['m1', "My problem is timing activities. I plan a forty minute lesson and either finish in twenty-five minutes with nothing left, or I am halfway through when the bell goes. The planning is fine on paper, the marking is manageable, it is purely the timing."],
        ['f1', 'That does come with practice, apparently. What did our mentor say?'],
        ['m1', 'She watched me on Thursday and her main suggestion was about questioning techniques. Apparently I ask a question and answer it myself two seconds later.'],
        ['f1', 'Everyone does that at first. Wait longer, she keeps telling me the same thing.'],
        ['m1', 'Questioning techniques, then, for both of us. Have you tried group work?'],
        ['f1', "I tried it once and it was chaos. But I have been reading about it, and the evidence is fairly clear that group work is most effective when roles are assigned. If you just say work in groups, three of them do nothing."],
        ['m1', 'Assigned roles. I will try that next week. How long is the placement altogether?'],
        ['f1', 'Eight weeks, and we are one week in.'],
        ['m1', 'Eight weeks. And we have to document everything, do we not?'],
        ['f1', 'Yes, we must keep a reflective journal, one entry per teaching day. I am already behind.'],
        ['m1', 'A reflective journal. And the observations, who does those?'],
        ['f1', 'Observations are carried out by the school mentor, not the university tutor. She comes in twice a week.'],
        ['m1', 'Right. Which classes do you have?'],
        ['f1', 'I teach mainly year seven, with one year nine group on Fridays.'],
        ['m1', 'Year seven, that explains the ability range. Shall we help each other with planning?'],
        ['f1', 'Yes, let us swap lesson plans by email each Sunday. It would save a lot of time.'],
        ['m1', 'Agreed. And when is everything due?'],
        ['f1', 'The final report is due at the end of May, along with the journal.'],
        ['m1', 'End of May. That is closer than it sounds.'],
        ['narrator', 'That is the end of Section 3. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 4,
      lines: [
        ['narrator', 'Section 4. You will hear part of a lecture about how people learn. First, you have some time to look at questions 31 to 40.'],
        ['narrator', 'Now listen carefully and answer questions 31 to 40.'],
        ['f1', "Good morning. Today I want to describe what cognitive psychology tells us about learning, and why so much of what students do naturally is ineffective."],
        ['f1', "Let us start with the architecture. When you encounter new information, it is first held briefly in working memory, which is the mental workspace where conscious thinking happens. Everything you learn passes through it."],
        ['f1', "And working memory is remarkably limited. It can hold only a small number of items at once, perhaps four for most adults, and only for a matter of seconds unless actively maintained. This single limitation explains a great deal about teaching."],
        ['f1', "There is a way round it. Grouping information into meaningful units is called chunking, and an expert differs from a novice largely in the size of their chunks. A chess master does not see thirty-two pieces; they see half a dozen familiar patterns."],
        ['f1', "Now to the practical findings, and the first concerns timing. Spacing study sessions across days produces more durable learning than the same total time in one block. Cramming produces good performance tomorrow and very little in a month, which is precisely the wrong trade for anyone taking a degree."],
        ['f1', "The second finding is about method. Rereading notes feels productive and does almost nothing. Testing yourself, which we call retrieval practice, is dramatically more effective, and the effect is not small. The act of pulling information out strengthens it in a way that putting it in again does not."],
        ['f1', "Third, mixing different problem types in one session, which is called interleaved practice, produces better long-term performance than practising one type at a time, even though it feels worse and performance during practice is lower."],
        ['f1', "That last point deserves emphasis, because it explains why students resist these methods. Learners often mistake fluency for real understanding. When material feels easy and familiar, we conclude we know it. But familiarity is not retrievability, and the methods that feel hardest are usually the ones that work."],
        ['f1', "A word on feedback. Feedback is most useful when it is specific. Telling a student the work is good, or that it is weak, changes nothing. Telling them which step was wrong and why does."],
        ['f1', "And a warning for anyone designing teaching materials. Excessive cognitive load prevents new material being processed at all. Decorative images, background music, and unnecessary detail compete for the same limited workspace as the thing you are trying to teach."],
        ['f1', "Finally, let me address something you will have heard about. The idea of fixed learning styles, that some people are visual learners and others auditory, is not supported by evidence. It has been tested repeatedly and matching instruction to a supposed style produces no benefit. What matters is matching the method to the material."],
        ['narrator', 'That is the end of Section 4. You now have one minute to check your answers.'],
      ],
    },
  ],
};
