/** Platform Test 4 — Listening transkripti. */

export default {
  test: 'Platform Test 4 — Health & Lifestyle',
  sections: [
    {
      sectionNumber: 1,
      lines: [
        ['narrator', 'Section 1. You will hear a man registering as a patient at a health centre. First, you have some time to look at questions 1 to 10.'],
        ['narrator', 'Now listen carefully and answer questions 1 to 10.'],
        ['f1', 'Good morning, Fairfield Health Centre. How can I help?'],
        ['m1', "Hello. I've just moved into the area and I need to register with a doctor."],
        ['f1', 'Certainly, I can take your details now. What is your surname?'],
        ['m1', "It's Okonkwo."],
        ['f1', 'Could you spell that for me?'],
        ['m1', 'O, K, O, N, K, W, O.'],
        ['f1', 'Okonkwo, thank you. And your date of birth?'],
        ['m1', 'The twelfth of May, nineteen ninety-eight.'],
        ['f1', 'Twelfth of May nineteen ninety-eight. And your current address?'],
        ['m1', "Eight Bramley Court. That's B, R, A, M, L, E, Y."],
        ['f1', 'Eight Bramley Court. Now, are you registering as a temporary or a permanent patient?'],
        ['m1', "Permanent, please. I've taken a job here so I'll be staying."],
        ['f1', 'Permanent patient, right. And where were you registered before?'],
        ['m1', 'My previous doctor was in Manchester. Should I bring anything from them?'],
        ['f1', "No, we'll request your records directly. Now, a few medical questions. Do you have any allergies?"],
        ['m1', "Yes, I'm allergic to penicillin. It's important that's on the file."],
        ['f1', "Allergic to penicillin. I've flagged that. Any long-term conditions or regular medication?"],
        ['m1', 'No, nothing at all.'],
        ['f1', "Good. Let me explain how things work here. Appointments can be booked from eight in the morning, either by phone or through the app. The early slots go quickly."],
        ['m1', 'From eight, right. And if I need a repeat prescription?'],
        ['f1', 'Order it online and allow three working days. Please do not leave it until you run out.'],
        ['m1', 'Three working days. Where would I collect it?'],
        ['f1', 'Most patients use the pharmacy on Chapel Street, which is about two minutes away and stays open until seven.'],
        ['m1', 'Chapel Street. That is convenient.'],
        ['f1', 'One more thing. All new patients are offered a health check with the practice nurse. I can book you in now if you like.'],
        ['m1', 'Yes please.'],
        ['f1', 'We have a space on the seventeenth of the month, at nine forty.'],
        ['m1', 'The seventeenth. That works. Thank you very much.'],
        ['narrator', 'That is the end of Section 1. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 2,
      lines: [
        ['narrator', 'Section 2. You will hear an introduction to a community fitness programme. First, you have some time to look at questions 11 to 20.'],
        ['narrator', 'Now listen carefully and answer questions 11 to 20.'],
        ['m1', 'Good evening everyone, and thank you for coming. My name is Ben and I run the Active Living programme here.'],
        ['m1', "Let me be clear about who this programme is for, because there is sometimes confusion. It is not designed for people training for competitions, and it is not a rehabilitation service for those recovering from surgery, although we can refer you. It is aimed at people who currently do little regular exercise and want to change that. If you have not exercised in years, you are exactly who we had in mind."],
        ['m1', "Now, how much should you do at the start? My strong advice is to begin with two sessions a week. Not daily. Almost everyone who starts with daily sessions has stopped entirely within a month, and I would far rather you were still here in December."],
        ['m1', "The most common mistake I see, and the one thing I really want to warn you against, is increasing intensity too quickly. Exercising outdoors is fine, free weights are fine, training with friends is positively encouraged. But going from nothing to very hard sessions is how people get injured and give up."],
        ['m1', "Some practical details. The programme lasts twelve weeks, which is long enough for the habit to establish itself."],
        ['m1', "Sessions are held in the community hall, next to the library, not in the leisure centre as some of you may have been told."],
        ['m1', "Please bring a bottle of water to every session. We have a tap but no cups."],
        ['m1', "The target we work towards is the standard recommendation of one hundred and fifty minutes of moderate activity a week. That sounds like a great deal, and it is roughly twenty minutes a day."],
        ['m1', "You will not be left to work things out alone. A qualified instructor is present at every session, so if something hurts, say so at the time."],
        ['m1', "The cost is forty pounds for the whole course, which works out at just over three pounds a session, and there are free places if that is a difficulty."],
        ['m1', "Finally, your progress is reviewed after six weeks. We take some simple measurements at the start and repeat them then, so you can see what has changed."],
        ['m1', 'Right, if you have questions, come and find me afterwards.'],
        ['narrator', 'That is the end of Section 2. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 3,
      lines: [
        ['narrator', 'Section 3. You will hear two students planning a public health survey. First, you have some time to look at questions 21 to 30.'],
        ['narrator', 'Now listen carefully and answer questions 21 to 30.'],
        ['f1', 'So, have you decided what our survey should be about?'],
        ['m1', 'I was going back and forth between diet and exercise, but I think sleep habits is the most interesting.'],
        ['f1', 'Sleep, yes. Nobody in our department has looked at it, and there is good evidence that students sleep badly.'],
        ['m1', 'Exactly. So, sleep habits it is. Now, my worry is about the responses themselves.'],
        ['f1', 'That people will not take part?'],
        ['m1', "No, I think we will get enough participants. My concern is that they will over-report positive behaviour. People say they sleep eight hours because they know they should, not because they do. It happens with every self-reported health survey."],
        ['f1', 'That is a fair point. We should mention it in the limitations, and maybe ask about last night specifically rather than in general.'],
        ['m1', 'Good idea, that usually helps. How are we going to collect it?'],
        ['f1', 'I was thinking paper forms, so we can hand them out in lectures.'],
        ['m1', "Paper means we have to type everything in afterwards. An online form is much faster, and we can put the link in the department newsletter."],
        ['f1', 'You are right, online form then. How many are we aiming for?'],
        ['m1', 'Two hundred students would give us something meaningful.'],
        ['f1', 'Two hundred. That should be achievable. And how long should it take to complete?'],
        ['m1', 'Under ten minutes, definitely. Beyond that the drop-out rate rises sharply.'],
        ['f1', 'Under ten minutes. And we must promise that responses will be kept anonymous, or nobody will answer honestly about sleep.'],
        ['m1', 'Anonymous, agreed. What about the answer format?'],
        ['f1', 'Let us use a five-point scale for the attitude questions. It is simple and people are familiar with it.'],
        ['m1', 'A five-point scale, fine. Now, who does what? Somebody needs to handle the paperwork for approval.'],
        ['f1', 'I will do the ethics application. I did one last year so I know the form.'],
        ['m1', 'Excellent, and I will handle the statistics once the data comes in. When do we start collecting?'],
        ['f1', 'Not the first week, everyone is disorganised. Let us begin in the second week of term.'],
        ['m1', 'Second week. And when do we present?'],
        ['f1', 'The final presentation is in December, so that gives us plenty of time to analyse it.'],
        ['m1', 'December. Right, I will draft the questions this weekend.'],
        ['narrator', 'That is the end of Section 3. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 4,
      lines: [
        ['narrator', 'Section 4. You will hear part of a lecture about nutrition and public health. First, you have some time to look at questions 31 to 40.'],
        ['narrator', 'Now listen carefully and answer questions 31 to 40.'],
        ['f1', "Good morning. Today I want to look at diet from a public health perspective, which means asking not what an individual should eat, but why populations eat what they do."],
        ['f1', "Let me start with the strongest finding in recent nutrition research. Diets high in ultra-processed foods are consistently linked to poorer health outcomes, including obesity, cardiovascular disease and early mortality. This holds even after adjusting for total calories, which suggests that processing itself, and not simply energy content, is part of the problem."],
        ['f1', "A second well-established relationship concerns sodium. Excess salt intake is associated with high blood pressure, and blood pressure is the single largest contributor to premature death worldwide. Most dietary salt does not come from the salt cellar; it is already in the food when you buy it."],
        ['f1', "On the positive side, fibre. Fibre is important for the health of the gut microbiome, the community of bacteria in the intestine, and populations eating traditional high-fibre diets show markedly greater microbial diversity than those eating a typical Western diet."],
        ['f1', "You will all know the standard advice to eat five portions of fruit and vegetables daily. The figure is somewhat arbitrary, chosen because it was memorable, and the evidence suggests more is better, but as public health messages go it has been unusually effective."],
        ['f1', "Now, why do people not follow this advice? Here is the uncomfortable finding. When researchers examine what actually determines purchases, food prices influence choices more than nutritional labels do. Information is cheap to provide and it changes very little; price changes behaviour immediately."],
        ['f1', "Which is why taxation has been tried. A tax on sugary drinks reduced consumption in several countries that introduced it, and in some cases manufacturers reformulated their products to fall below the threshold, which was arguably the larger effect."],
        ['f1', "Access matters as well as price. Areas with poor access to fresh food are called food deserts, and they are typically neighbourhoods with low car ownership and no supermarket within walking distance. Telling residents to eat more vegetables is of limited use if the nearest ones are three bus stops away."],
        ['f1', "One intervention with good evidence behind it is in schools. School meal standards, where they have been introduced and enforced, have improved children's diets measurably, including among those who eat poorly at home."],
        ['f1', "A word of caution about all such interventions. Nutritional advice must take cultural traditions into account. Programmes that ignore what people actually cook and eat, and simply prescribe an unfamiliar diet, are rejected and waste the money spent on them."],
        ['f1', "Which brings me to my main argument. We tend to describe diet as a matter of individual choice, and in one sense it is. But individual choice is shaped by the food environment: what is available, what it costs, what is advertised and what is normal. Change the environment and the choices change without anybody being lectured."],
        ['narrator', 'That is the end of Section 4. You now have one minute to check your answers.'],
      ],
    },
  ],
};
