/** Platform Test 5 — Listening transkripti. */

export default {
  test: 'Platform Test 5 — Technology & Work',
  sections: [
    {
      sectionNumber: 1,
      lines: [
        ['narrator', 'Section 1. You will hear a man enquiring about a coworking space. First, you have some time to look at questions 1 to 10.'],
        ['narrator', 'Now listen carefully and answer questions 1 to 10.'],
        ['f1', 'Good afternoon, Northgate Workspace.'],
        ['m1', "Hello. I'm looking for somewhere to work a few days a week and a colleague recommended you."],
        ['f1', 'Of course. Can I take your name?'],
        ['m1', "Yes, Daniel Ferreira. That's F, E, R, R, E, I, R, A."],
        ['f1', 'Ferreira, thank you. Are you looking for a fixed desk or a hot desk?'],
        ['m1', "What's the difference exactly?"],
        ['f1', 'A fixed desk is yours permanently, with storage, at two hundred and sixty a month. A hot desk means you sit wherever is free.'],
        ['m1', "I'm only in two or three days a week, so a hot desk makes more sense."],
        ['f1', 'A hot desk it is. That comes to one hundred and eighty pounds a month.'],
        ['m1', 'One hundred and eighty. And what hours can I come in?'],
        ['f1', 'Members have access twenty-four hours a day, using a code on the door. Non-members can only use the café area during office hours.'],
        ['m1', 'Twenty-four hours, useful. Do you have meeting rooms?'],
        ['f1', 'We have three. They are fifteen pounds per hour for members, and you book them through the app.'],
        ['m1', 'Fifteen an hour. Where exactly are you? I know the area vaguely.'],
        ['f1', 'The building is on Hanover Street, the old red-brick one opposite the bank.'],
        ['m1', 'Hanover Street. And the nearest station?'],
        ['f1', 'Victoria Park, about six minutes on foot.'],
        ['m1', 'Victoria Park, that suits me. Could I try it before committing?'],
        ['f1', 'Yes, we offer a free trial lasting three days. Most people take it up.'],
        ['m1', 'Three days, excellent. Are there any rules I should know about?'],
        ['f1', 'One main one. Members must not use the quiet area for phone calls. There are booths for that, and people get quite annoyed if the rule is ignored.'],
        ['m1', 'No calls in the quiet area, understood. And if I want to leave?'],
        ['f1', 'The contract has a one month notice period, so it is quite flexible.'],
        ['m1', 'One month. That is all very clear. Could I book the trial for next Monday?'],
        ['f1', 'Certainly, I will put you down and send the door code the day before.'],
        ['narrator', 'That is the end of Section 1. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 2,
      lines: [
        ['narrator', 'Section 2. You will hear a briefing about a new recycling scheme. First, you have some time to look at questions 11 to 20.'],
        ['narrator', 'Now listen carefully and answer questions 11 to 20.'],
        ['m1', 'Good evening. I am here from the council to explain the changes to recycling that start next month.'],
        ['m1', "First, who this affects. There has been some confusion about this. The new scheme applies to all households in the district, whether you live in a house, a flat, in town or in the villages. Businesses have a separate arrangement and are not covered tonight."],
        ['m1', "The main change is how we handle electronic items. Please do not put them in any of your bins, and do not leave them beside the bin, which some people have been doing. Electronic items should be taken to a collection point, and there are now nine of these across the district, including at both supermarkets."],
        ['m1', "Now, the mistake we see most often. It is not the wrong bag, and it is not food waste, which people are generally good about. The commonest problem by a wide margin is not rinsing containers. A single unwashed jar can contaminate an entire load, and that load then goes to landfill. A quick rinse is all that is needed."],
        ['m1', "Some practical details. Collections take place every two weeks, alternating between recycling and general waste."],
        ['m1', "Batteries are a particular hazard because they cause fires in the collection lorries. Batteries must be placed in a separate clear bag and left on top of the bin, not inside it."],
        ['m1', "For anything you cannot put out, the recycling centre on Mill Lane is open seven days, and at weekends it stays open until six."],
        ['m1', "Large items such as furniture require a booked collection. You can arrange that online and there is a small charge."],
        ['m1', "As for why we are doing this, the council aims to recycle sixty-five per cent of waste by twenty thirty. We are currently at forty-one, so there is some way to go."],
        ['m1', "If your bin is damaged or missing, residents can request a new bin online and it will normally arrive within a fortnight."],
        ['m1', "Finally, we know not everyone finds English easy, so information leaflets are available in six languages, and there is a video with subtitles on the council website."],
        ['m1', 'I am happy to take questions now.'],
        ['narrator', 'That is the end of Section 2. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 3,
      lines: [
        ['narrator', 'Section 3. You will hear two students preparing a presentation about automation. First, you have some time to look at questions 21 to 30.'],
        ['narrator', 'Now listen carefully and answer questions 21 to 30.'],
        ['f1', 'Right, we need to narrow this down. Automation is a huge subject.'],
        ['m1', 'It is. I assumed we would do manufacturing, since that is the obvious example.'],
        ['f1', "Everyone does manufacturing. I think office work is far more interesting, because that is where the change is happening now and nobody expected it. Robots on production lines are forty years old."],
        ['m1', 'That is a good argument. Office work then. What about our introduction?'],
        ['f1', "Honestly? It is too technical. You have got three paragraphs on machine learning architectures before we even mention a job. The audience are second-year students, not engineers."],
        ['m1', 'Fair. I will cut it right back and start with a concrete example instead.'],
        ['f1', 'Much better. Should we include some primary material?'],
        ['m1', 'I was thinking we could interview someone. A professor would be easy to arrange.'],
        ['f1', "A professor will just repeat what is already in the reading. An interview with a company manager would be far more valuable, someone who has actually introduced these systems and can say what happened to the staff."],
        ['m1', 'You are right. I know someone at a logistics firm who might agree.'],
        ['f1', 'Perfect. Now, what is worrying you? You have been looking at the clock.'],
        ['m1', 'The time limit, mainly. The presentation must last fifteen minutes and we have enough material for forty.'],
        ['f1', 'Then we cut. Fifteen minutes is not long. How many slides?'],
        ['m1', 'We should use no more than twelve slides. About a minute each, plus discussion.'],
        ['f1', 'Twelve, agreed. I will prepare the conclusion section, since I have the strongest view about where this is going.'],
        ['m1', 'And I will do the introduction and the case study. When shall we rehearse?'],
        ['f1', 'Sunday evening? That gives us the weekend to finish the slides.'],
        ['m1', 'Sunday evening works. Oh, and Dr Hale wants something in advance.'],
        ['f1', 'What does she need?'],
        ['m1', 'A list of sources, submitted before the session, so she can check we are not relying on blogs.'],
        ['f1', 'A list of sources. I will put that together. And where are we presenting?'],
        ['m1', 'Room three zero four, in the main building.'],
        ['f1', 'Room three zero four. Right, let us start cutting that introduction.'],
        ['narrator', 'That is the end of Section 3. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 4,
      lines: [
        ['narrator', 'Section 4. You will hear part of a lecture about skills for a changing labour market. First, you have some time to look at questions 31 to 40.'],
        ['narrator', 'Now listen carefully and answer questions 31 to 40.'],
        ['m1', "Good afternoon. Today I want to examine which kinds of work are most exposed to automation, and what that implies for the skills you should be developing."],
        ['m1', "The first thing to understand is that the vulnerability of a job has very little to do with how much education it required. What matters is whether the task is routine, in the technical sense of following predictable rules. Routine cognitive tasks are the most easily automated: processing invoices, checking documents against criteria, producing standard reports. These were considered secure white-collar work a generation ago."],
        ['m1', "By contrast, tasks that resist automation include those requiring manual dexterity in unpredictable settings. A machine can assemble a car far better than a person, because the environment is controlled. It cannot yet repair a boiler in an unfamiliar house."],
        ['m1', "Now, an important correction to how this is usually discussed. Automation tends to change tasks rather than eliminate whole occupations. Most jobs are bundles of many tasks, some automatable and some not, and what typically happens is that the composition of the job shifts."],
        ['m1', "Which brings us to what is becoming more valuable. Demand is rising fastest for skills involving social intelligence: negotiation, persuasion, care, teaching, managing disagreement. These have proved extraordinarily difficult to automate and, not coincidentally, they have historically been undervalued and underpaid."],
        ['m1', "The structural change you should plan for is this. Workers now change careers far more often than previous generations, several times in a working life rather than once or never. The expectation of a single occupation is gone."],
        ['m1', "Which is why lifelong learning has become a policy priority in almost every developed economy, although the policies themselves are frequently thin."],
        ['m1', "One visible response is the growth of shorter qualifications. Short courses leading to a certificate, often taken while working, are increasingly popular, particularly where employers recognise them directly."],
        ['m1', "There is a persistent gap here. Employers across sectors report a shortage of workers with digital skills, and by this they usually mean not programming but competence with data, spreadsheets and systems."],
        ['m1', "The evidence on retraining is worth knowing. Programmes that simply offer courses have disappointing results. Retraining works best when combined with income support, because a worker with no savings cannot afford to spend six months learning anything."],
        ['m1', "I will finish with the point I want you to take away. The challenge is not that machines will do everything. It is the pace of change. Technologies that took two generations to spread now spread in one, and institutions built for the older rhythm are struggling to keep up."],
        ['narrator', 'That is the end of Section 4. You now have one minute to check your answers.'],
      ],
    },
  ],
};
