/** Platform Test 3 — Listening transkripti. */

export default {
  test: 'Platform Test 3 — History & Society',
  sections: [
    {
      sectionNumber: 1,
      lines: [
        ['narrator', 'Section 1. You will hear a woman booking places on a guided historical walk. First, you have some time to look at questions 1 to 10.'],
        ['narrator', 'Now listen carefully and answer questions 1 to 10.'],
        ['m1', 'Good morning, Old Town Walking Tours.'],
        ['f1', "Hello. I'd like to book places on one of your historical walks, please."],
        ['m1', 'Of course. Can I take a name for the booking?'],
        ['f1', "Yes, it's Julia Renshaw."],
        ['m1', 'Could you spell the surname?'],
        ['f1', 'R, E, N, S, H, A, W.'],
        ['m1', 'Renshaw, thank you. And how many people will there be?'],
        ['f1', "There'll be six of us. Four adults and two students."],
        ['m1', 'Six in total. And which date were you thinking of?'],
        ['f1', 'We were hoping for a Saturday. Is the nineteenth of April possible?'],
        ['m1', 'Let me check. The nineteenth of April, yes, we have space on the morning walk.'],
        ['f1', 'The nineteenth, wonderful. And where do we meet?'],
        ['m1', 'The walk begins outside the cathedral, by the west door. Not inside, because we cannot gather in there.'],
        ['f1', 'Outside the cathedral. And how long does it last?'],
        ['m1', 'Two hours, including a short stop halfway.'],
        ['f1', 'Two hours is fine. What does it cost?'],
        ['m1', 'The price is twelve pounds per adult.'],
        ['f1', 'Twelve pounds each. And you mentioned a student rate?'],
        ['m1', 'Yes, students receive a discount of twenty-five per cent, with a valid card.'],
        ['f1', 'Twenty-five per cent, good, they will have their cards. Who will be taking us round?'],
        ['m1', 'On Saturday mornings the guide is Marcus. He has been doing these walks for over ten years and knows the archives extremely well.'],
        ['f1', 'Marcus, right. Is there anything we need to bring?'],
        ['m1', 'Nothing special, but do tell everyone to wear comfortable shoes. Some of the streets are cobbled and we cover about three kilometres.'],
        ['f1', 'Comfortable shoes, I will pass that on. And how do we pay?'],
        ['m1', 'We ask for payment seven days before the walk. I will email you a link this afternoon.'],
        ['f1', 'Seven days beforehand. That is all clear. Thank you very much.'],
        ['m1', 'Thank you. We look forward to seeing you on the nineteenth.'],
        ['narrator', 'That is the end of Section 1. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 2,
      lines: [
        ['narrator', 'Section 2. You will hear an announcement about a local history museum. First, you have some time to look at questions 11 to 20.'],
        ['narrator', 'Now listen carefully and answer questions 11 to 20.'],
        ['f1', 'Good morning and welcome to Marlowe Local History Museum. Let me tell you a little about the museum before you begin.'],
        ['f1', "Visitors often ask about the building itself, which is unusual. It was not built as a school, although the windows suggest it, and it was never a courthouse or a hospital. It was in fact a warehouse, built in eighteen sixty for the wool trade, which is why the ground floor is so open."],
        ['f1', "Our permanent galleries cover the whole history of the town. The new temporary exhibition, which opened last month, focuses on wartime life. It draws entirely on material donated by local families, including letters, ration books and photographs, and it has been our most popular exhibition so far."],
        ['f1', "Admission. General entry is six pounds. There is no free day, I am afraid, and residency in the town makes no difference. However, entry is free for children under sixteen, whether or not they are accompanied."],
        ['f1', "Some background. The museum opened to the public in nineteen eighty-seven, in what was then a semi-derelict building, and it has been extended twice since."],
        ['f1', "Behind the galleries we hold a substantial archive. It contains over forty thousand photographs of the town and the surrounding villages, many of them not yet digitised."],
        ['f1', "If you wish to consult the archive, please note that researchers must book the reading room in advance, as there are only six places and staff need to retrieve material beforehand."],
        ['f1', "One project I would particularly recommend is our oral history collection. Between two thousand and two thousand and eight, volunteers recorded one hundred and fifty interviews with older residents. You can listen to extracts on the first floor."],
        ['f1', "Guided tours run at two o'clock each afternoon and last about forty minutes. There is no need to book."],
        ['f1', "If you would like refreshments, the café is located on the ground floor, at the far end, next to the shop."],
        ['f1', "And finally, do check before travelling, because the museum is closed every Monday, including bank holidays."],
        ['f1', 'That is everything. Please do ask the stewards if you have any questions.'],
        ['narrator', 'That is the end of Section 2. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 3,
      lines: [
        ['narrator', 'Section 3. You will hear a student discussing a history essay with her tutor. First, you have some time to look at questions 21 to 30.'],
        ['narrator', 'Now listen carefully and answer questions 21 to 30.'],
        ['m1', 'Come in, Sophie. You wanted to talk about the essay title.'],
        ['f1', "Yes, thank you. I've chosen to write about industrial change in the north of England."],
        ['m1', 'Right. And how long is the essay?'],
        ['f1', 'Around four thousand words.'],
        ['m1', "Four thousand words, and you want to cover industrial change across a whole region. Sophie, that topic is far too broad. You could write a book on it, and people have."],
        ['f1', "I did wonder. So should I narrow it down?"],
        ['m1', "You must. My advice would be to take a single decade and examine it properly. Pick the eighteen forties, for instance, and you can actually use evidence rather than summarising other people's summaries."],
        ['f1', 'A single decade. That does sound more manageable. I was planning to use a lot of primary sources.'],
        ['m1', 'Good, but be careful with them. There is a problem you need to acknowledge.'],
        ['f1', 'Because they are hard to access?'],
        ['m1', "No, access is not the issue, most are catalogued. The difficulty is that they may be unrepresentative. The documents that survive tend to be those written by literate, propertied people, and preserved because someone thought them worth keeping. You are not hearing from everybody."],
        ['f1', 'So I should say that explicitly in the essay.'],
        ['m1', 'Say it explicitly, yes. Now, on reading. There is a very useful chapter by Whitfield that sets out the debate clearly. Start there.'],
        ['f1', 'Whitfield, I will look it up. Is that a primary source?'],
        ['m1', 'No, that is a modern historian, so it counts as one of your secondary sources. You need both, but do not let the secondary material do your thinking for you.'],
        ['f1', 'Understood. When would you like to see a draft?'],
        ['m1', 'Let us say a first draft in week nine. That leaves time to revise.'],
        ['f1', 'Week nine. And is there anything else I should watch out for?'],
        ['m1', 'One thing. Do not rely on a single author, however good. If your argument collapses when one historian turns out to be wrong, it was never your argument.'],
        ['f1', 'That makes sense. Should I visit an archive?'],
        ['m1', 'It would strengthen the work considerably. The county archive holds the relevant material and it is only twenty minutes away.'],
        ['f1', 'The county archive. I will go next week.'],
        ['m1', 'Good. Shall we meet again once you have been?'],
        ['f1', 'Yes please. Are you free on Wednesday?'],
        ['m1', 'Wednesday morning suits me. Ten o clock.'],
        ['f1', 'Wednesday morning. Thank you very much.'],
        ['narrator', 'That is the end of Section 3. You now have half a minute to check your answers.'],
      ],
    },

    {
      sectionNumber: 4,
      lines: [
        ['narrator', 'Section 4. You will hear part of a lecture about cities in the ancient world. First, you have some time to look at questions 31 to 40.'],
        ['narrator', 'Now listen carefully and answer questions 31 to 40.'],
        ['f1', "Good morning. Today I want to consider how the first cities came into existence, and what conditions made them possible."],
        ['f1', "The earliest cities we know of appeared in Mesopotamia around four thousand BCE, in the region between the Tigris and the Euphrates. Comparable developments occurred later in the Indus valley, in China and in Mesoamerica."],
        ['f1', "The precondition for all of them is agricultural. A city is a settlement in which most people do not grow their own food. That is only possible if farmers produce more than they consume, so every early city depended on a reliable food surplus. No surplus, no city."],
        ['f1', "Once a section of the population is freed from farming, something interesting follows. People begin to do one thing well rather than everything adequately. We see the emergence of specialised crafts: potters, weavers, metalworkers, scribes. Almost everything we think of as civilisation follows from that division of labour."],
        ['f1', "Location was not arbitrary. Early cities were almost invariably built beside a river, which provided water for irrigation, a means of transport, and a defensible boundary."],
        ['f1', "Most were walled, and it is worth being careful about why. The obvious answer is defence, and that is part of it. But walls also concentrated movement into a small number of gates, and gates are where goods can be counted and taxed. So walls served both defence and the control of trade."],
        ['f1', "Let me jump forward to the largest ancient city we can estimate with any confidence. At its height, Rome may have reached a population of one million, a figure no European city would match again for over fifteen hundred years."],
        ['f1', "Supplying such a city was an engineering problem. Roman cities relied on aqueducts to bring fresh water in from the hills, sometimes over many kilometres, using nothing but a carefully maintained gradient."],
        ['f1', "But we should not romanticise them. Ancient cities were extremely unhealthy places. Poor sanitation meant that waterborne disease was constant, and death rates in cities consistently exceeded birth rates."],
        ['f1', "Which raises an obvious question: if more people died than were born, how did cities grow at all? The answer is that urban populations were sustained by continuous migration from the countryside. Cities consumed people, and the surrounding villages supplied them."],
        ['f1', "That leads to the point I want to leave you with. Cities concentrate wealth, knowledge and opportunity, and simultaneously they concentrate risk: disease, fire, and dependence on food grown elsewhere. That double character has not changed at all in six thousand years."],
        ['narrator', 'That is the end of Section 4. You now have one minute to check your answers.'],
      ],
    },
  ],
};
